---
title: "Infection and Disease by Month of Birth"
output: html_document
date: "2024-03-14"
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(plotly)

source(file = "/Users/lsh2301561/Desktop/rsv_disruption/code/plot/plot_births.R")
```

```{r data, include=FALSE}
births_year <- readRDS(file = "/Users/lsh2301561/Desktop/rsv_disruption/output/data/births_year.rds")
births_age <- readRDS(file = "/Users/lsh2301561/Desktop/rsv_disruption/output/data/births_age.rds")

```

## Infections

First infection by month of birth

```{r inf, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12}
inf <- subplot(
  plot_infections(births_year %>% filter(month_born == "Jan")),
  plot_infections(births_year %>% filter(month_born == "Feb")),
  plot_infections(births_year %>% filter(month_born == "Mar")),
  plot_infections(births_year %>% filter(month_born == "Apr")),
  plot_infections(births_year %>% filter(month_born == "May")),
  plot_infections(births_year %>% filter(month_born == "Jun")),
  plot_infections(births_year %>% filter(month_born == "Jul")),
  plot_infections(births_year %>% filter(month_born == "Aug")),
  plot_infections(births_year %>% filter(month_born == "Sep")),
  plot_infections(births_year %>% filter(month_born == "Oct")),
  plot_infections(births_year %>% filter(month_born == "Nov")),
  plot_infections(births_year %>% filter(month_born == "Dec")),
  nrows = 4,
  shareX = FALSE,
  shareY = TRUE,
  margin = c(0.02, 0.02, 0.05, 0.06)
)

for(n in 6:60){
  inf[["x"]][["data"]][[n]][["showlegend"]] <-  FALSE
}

inf
```

Cumulative first infection by month of birth

```{r cum_inf, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12}
cum_inf <- plot_cumpropinf(births_year)

cum_inf
```

Age at first infection by month of birth

```{r age_inf, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12}
age_inf <- subplot(
  plot_age(births_age %>% filter(month_born == "Jan"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Feb"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Mar"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Apr"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "May"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Jun"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Jul"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Aug"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Sep"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Oct"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Nov"), types = "infected"),
  plot_age(births_age %>% filter(month_born == "Dec"), types = "infected"),
  nrows = 4,
  shareX = FALSE,
  shareY = TRUE,
  margin = c(0.02, 0.02, 0.03, 0.05)
)

for(n in 6:60){
  age_inf[["x"]][["data"]][[n]][["showlegend"]] <-  FALSE
}

age_inf
```

## Disease

First occurence of disease by month of birth

```{r dis, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12}
dis <- subplot(
  plot_disease(births_year %>% filter(month_born == "Jan")),
  plot_disease(births_year %>% filter(month_born == "Feb")),
  plot_disease(births_year %>% filter(month_born == "Mar")),
  plot_disease(births_year %>% filter(month_born == "Apr")),
  plot_disease(births_year %>% filter(month_born == "May")),
  plot_disease(births_year %>% filter(month_born == "Jun")),
  plot_disease(births_year %>% filter(month_born == "Jul")),
  plot_disease(births_year %>% filter(month_born == "Aug")),
  plot_disease(births_year %>% filter(month_born == "Sep")),
  plot_disease(births_year %>% filter(month_born == "Oct")),
  plot_disease(births_year %>% filter(month_born == "Nov")),
  plot_disease(births_year %>% filter(month_born == "Dec")),
  nrows = 4,
  shareX = FALSE,
  shareY = TRUE,
  margin = c(0.02, 0.02, 0.05, 0.06)
)

for(n in 6:60){
  dis[["x"]][["data"]][[n]][["showlegend"]] <-  FALSE
}

dis
```

Cumulative first occurrence of disease by month of birth

```{r cum_dis, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12}
cum_dis <- plot_cumpropdis(births_year)

cum_dis
```

Age at first occurence of disease by month of birth

```{r age_dis, echo=FALSE, message=FALSE, warning=FALSE, fig.width=12}
age_dis <- subplot(
  plot_age(births_age %>% filter(month_born == "Jan"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Feb"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Mar"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Apr"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "May"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Jun"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Jul"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Aug"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Sep"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Oct"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Nov"), types = "disease"),
  plot_age(births_age %>% filter(month_born == "Dec"), types = "disease"),
  nrows = 4,
  shareX = FALSE,
  shareY = TRUE,
  margin = c(0.02, 0.02, 0.03, 0.05)
)

for(n in 6:60){
  age_dis[["x"]][["data"]][[n]][["showlegend"]] <-  FALSE
}

age_dis
```

## Summary
