---
title: "plot_births"
output: html_document
date: "2024-02-22"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tidyr)
library(zoo)
library(viridisLite)
library(plotly)
```

```{r data, include = FALSE}
births_january <- readRDS(file = "/Users/lsh2301561/Desktop/rsv_disruption/output/data/births_january.rds")
births_july <- readRDS(file = "/Users/lsh2301561/Desktop/rsv_disruption/output/data/births_july.rds")
```
## Monthly Infections

Monthly infections for one month of births.

```{r inf, echo = FALSE}
births_january %>% 
  group_by(time, month) %>% 
  summarise(susceptible = sum(susceptible_sub),
            infected = sum(infected)) %>% 
  ungroup() %>% 
  plot_ly() %>% 
  add_trace(x = ~time,
            y = ~infected,
            type = "scatter",
            mode = "lines",
            text = ~month,
            hovertemplate = paste('<b>Month</b>: %{text}',
                                  '<br><b>Infected</b>: %{y}',
                                  '<extra></extra>')) %>% 
  layout(xaxis = list(title = "Time",
                      tickmode = "array",
                      ticktext = list("January", "July", "January", "July", "January", "July", "January"),
                      tickvals = list(1, 7, 13, 19, 25, 31, 37)),
         yaxis = list(title = "Count"))

  # ggplot() +
  # geom_line(aes(x = time, y = infected)) +
  # scale_x_continuous(breaks = seq(1, 37, 6), labels = c(rep(c("January", "July"), rep), "January")) +
  # theme_bw() +
  # labs(x = "",
  #      y = "Count",
  #      title = "January Babies")

births_july %>% 
  group_by(time, month) %>% 
  summarise(susceptible = sum(susceptible_sub),
            infected = sum(infected)) %>% 
  ungroup() %>% 
  plot_ly() %>% 
  add_trace(x = ~time,
            y = ~infected,
            type = "scatter",
            mode = "lines",
            text = ~month,
            hovertemplate = paste('<b>Month</b>: %{text}',
                                  '<br><b>Infected</b>: %{y}',
                                  '<extra></extra>')) %>% 
  layout(xaxis = list(title = "Time",
                      tickmode = "array",
                      ticktext = list("July", "January", "July", "January", "July", "January", "July"),
                      tickvals = list(1, 7, 13, 19, 25, 31, 37)),
         yaxis = list(title = "Count"))
  
  # ggplot() +
  # geom_line(aes(x = time, y = infected)) +
  # scale_x_continuous(breaks = seq(1, 37, 6), labels = c(rep(c("July", "January"), rep), "July")) +
  # theme_bw() +
  # labs(x = "",
  #      y = "Count",
  #      title = "July Babies")

```

## Cumulative Infections

Cumulative proportion of babies infected over a period of 3 years for one month of births.

```{r cum_inf, echo = FALSE}
births_january %>% 
  group_by(time, month) %>% 
  summarise(susceptible = sum(susceptible_sub),
            infected = sum(infected)) %>% 
  ungroup() %>% 
  mutate(cum_sum = cumsum(infected),
         prop = (cum_sum/61942)*100) %>% 
    plot_ly() %>% 
  add_trace(x = ~time,
            y = ~prop,
            type = "scatter",
            mode = "lines",
            text = ~month,
            hovertemplate = paste('<b>Month</b>: %{text}',
                                  '<br><b>Proportion Infected</b>: %{y}',
                                  '<extra></extra>')) %>% 
  layout(xaxis = list(title = "Time",
                      tickmode = "array",
                      ticktext = list("January", "July", "January", "July", "January", "July", "January"),
                      tickvals = list(1, 7, 13, 19, 25, 31, 37)),
         yaxis = list(title = "Proportion Infected (%)"))

  # ggplot() +
  # geom_line(aes(x = time, y = prop)) +
  # scale_x_continuous(breaks = seq(1, 37, 6), labels = c(rep(c("January", "July"), rep), "January")) +
  # theme_bw() +
  # labs(x = "",
  #      y = "Proportion Infected (%)",
  #      title = "January Babies")

births_july %>% 
  group_by(time, month) %>% 
  summarise(susceptible = sum(susceptible_sub),
            infected = sum(infected)) %>% 
  ungroup() %>% 
  mutate(cum_sum = cumsum(infected),
         prop = (cum_sum/61942)*100) %>% 
    plot_ly() %>% 
  add_trace(x = ~time,
            y = ~prop,
            type = "scatter",
            mode = "lines",
            text = ~month,
            hovertemplate = paste('<b>Month</b>: %{text}',
                                  '<br><b>Proportion Infected</b>: %{y}',
                                  '<extra></extra>')) %>% 
  layout(xaxis = list(title = "Time",
                      tickmode = "array",
                      ticktext = list("July", "January", "July", "January", "July", "January", "January"),
                      tickvals = list(1, 7, 13, 19, 25, 31, 37)),
         yaxis = list(title = "Proportion Infected (%)"))

  # ggplot() +
  # geom_line(aes(x = time, y = prop)) +
  # scale_x_continuous(breaks = seq(1, 37, 6), labels = c(rep(c("July", "January"), rep), "July")) +
  # theme_bw() +
  # labs(x = "",
  #      y = "Proportion Infected (%)",
  #      title = "July Babies")
```

## Base rate

Monthly infections for one month of births where babies are born with different levels of immunity.

```{r base, echo = FALSE}
births_january %>% 
  ggplot() +
  geom_line(aes(x = time, y = infected, colour = level)) +
  scale_x_continuous(breaks = seq(1, 36, 6), labels = c(rep(c("January", "July"), rep))) +
  scale_colour_viridis_d(option = "H") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "",
       y = "Count",
       colour = "Immunity Level",
       title = "January Babies")

births_july %>% 
  ggplot() +
  geom_line(aes(x = time, y = infected, colour = level)) +
  scale_x_continuous(breaks = seq(1, 36, 6), labels = c(rep(c("January", "July"), rep))) +
  scale_colour_viridis_d(option = "H") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "",
       y = "Count",
       colour = "Immunity Level",
       title = "July Babies")
```
## Rate of infection


```{r infection, eval = FALSE}
```

## Rate of disease


```{r disease, eval = FALSE}
```